### ISSUE TITLE
Screen Denisites / Resolutions Errors.

### ISSUE THREAD

**Issue by cdowdy** [cdowdy/boltresponsiveimages#1]
If the resolutions in the config   

``` yaml
resSwitch:
  widths: [ 300, 480, 960, 1600 ]
  heights: [ 0 ]
  widthDensity: x
  resolutions: [ '1', '1.5', '2', '3', '3.5' ]
  cropping: fit
  altText:
  class:  
```

Dont match the number of widths or heights for generating a thumbnail and display_errors or error reporting is on a warning that isn't helpful is displayed.  

![boltrespimg-error](https://cloud.githubusercontent.com/assets/5969974/12454359/2360dfcc-bf65-11e5-8e9f-054675c7426c.PNG)  

This also prevents a proper srcset from being generated.  

``` html

<img srcset=""
        src="/bolt-respimg/thumbs/300x0f/analog-camera-photography-vintage-1844.jpg"
        alt="analog-camera-photography-vintage-1844">  
```

This is no bueno haha.  Quick Fix, but not long term, incoming!
