### ISSUE TITLE
using w descriptor classes have not spaces between each class

### ISSUE THREAD

**Issue by cdowdy** [cdowdy/boltresponsiveimages#7]
using w descriptor with an HTML class added like so:  

``` yaml
demos_bolt:
    widths: [ 320, 520, 900 ]
    heights: [ 0 ]
    widthDensity: 'w'
    sizes: [ '(min-width: 800px) 30vw', ' 90vw' ]
    class: [one, two, three]  
```

the rendered HTML is wrroooooooooooong  

``` html
<img sizes="(min-width: 800px) 30vw, 90vw"
    srcset="/bolt-respimg/thumbs/320x0r/image.jpg 320w,/bolt-respimg/thumbs/520x0r/image.jpg 520w,/bolt-respimg/thumbs/900x0r/image.jpg 900w"
    src="/bolt-respimg/thumbs/320x0r/image.jpg"
    alt="image alt text here"
    class="onetwothree">  <!-- badness be here --> 
```
